import type { Metadata } from 'next'
import '../assets/css/globals.css'
import { Header } from '@/components/Header'
import { Toaster } from 'react-hot-toast'
import { useAuth } from '@/hooks/useAuth'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic'; // fix cookies error when build

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const { isAuth, info } = await useAuth();  
  
  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-7xl px-6 lg:px-8 min-h-[120vh]">
          <Header isAuth={isAuth} info={info} />
          {children}
        </div>

        <Toaster position="top-right" toastOptions={ { duration: 3000 } } />
      </body>
    </html>
  )
}
